### PR TITLE
fix #1041 Ensure one and the same MicrometerChannelMetricsRecorder instance is used when enabling metrics

### LINKED ISSUE #1041: [TCPCLient - Metrics] Metrics create a Gauge per connection instead of only one before
Stack Overflow question here: https://stackoverflow.com/questions/60833197/reactor-netty-change-of-behavior-in-connection-pool-metrics

## Expected behavior
When activating metrics on the a TCP Client, we are able to track the total (active and pending) number of connections.

In Spring Boot 2.2.2.RELEASE (Reactor Netty 0.9.2.RELEASE), I had exactly one Gauge, no matter how many calls I do to my app.

```[POOL STATUS]

# HELP reactor_netty_connection_provider_hello_provider_total_connections The number of all connections, active or idle.
# TYPE reactor_netty_connection_provider_hello_provider_total_connections gauge
reactor_netty_connection_provider_hello_provider_total_connections{id="632562051",remote_address="www.google.fr:443",} 4.0
```

## Actual Behavior
In Spring Boot 2.2.5.RELEASE (Reactor Netty 0.9.5.RELLEASE), it seems I have a Gauge per established connection.

Which means I'm not able to know the actual pool size:

```[POOL STATUS]

# HELP reactor_netty_connection_provider_hello_provider_total_connections The number of all connections, active or idle.
# TYPE reactor_netty_connection_provider_hello_provider_total_connections gauge
reactor_netty_connection_provider_hello_provider_total_connections{id="-1991983041",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="1841778682",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-1928743100",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-1336097344",remote_address="www.google.fr:443",} 1.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-788261260",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-1834957872",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="2007052161",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-439458947",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-1285301951",remote_address="www.google.fr:443",} 1.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-1857034994",remote_address="www.google.fr:443",} 1.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-482930910",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="4893797",remote_address="www.google.fr:443",} 1.0
reactor_netty_connection_provider_hello_provider_total_connections{id="1545030655",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="544404070",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="375949406",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="2086700363",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="1576104761",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-804315975",remote_address="www.google.fr:443",} 0.0
reactor_netty_connection_provider_hello_provider_total_connections{id="1391945237",remote_address="www.google.fr:443",} 1.0
reactor_netty_connection_provider_hello_provider_total_connections{id="-554386199",remote_address="www.google.fr:443",} 1.0
```

## Steps to Reproduce
I created 2 dumb Spring Boot projects with both versions. It has just a web client that performs a call on a given search engine and gets the status code. 

The web client and the pool are created this way:

```java
@Bean
    public WebClient getWebClient(final WebClient.Builder builder) {
        return builder
            .clientConnector(
                new ReactorClientHttpConnector(
                    HttpClient
                        .create(ConnectionProvider.fixed("hello_provider", 5))
                        .secure()
                        .tcpConfiguration(tcpClient -> tcpClient.metrics(true)
                                                                .doOnConnected(connection -> connection.addHandlerLast(
                                                                    new ReadTimeoutHandler(1_000, TimeUnit.MILLISECONDS))
                                                                )
                                                                .doOnConnected(connection -> connection.addHandlerLast(
                                                                    new WriteTimeoutHandler(1_000, TimeUnit.MILLISECONDS))
                                                                )
                                                                .option(ChannelOption.SO_KEEPALIVE, true)
                                                                .option(ChannelOption.TCP_NODELAY, true)
                                                                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 1_000)
                        )
                )
            )
            .baseUrl("https://www.google.fr")
            .build();
    }
```

_NB: just replace fixed(...) by create(...) in the 0.9.5.RELEASE_

The Service:

```java
@Service
@RequiredArgsConstructor
public class HelloService {

    private final WebClient webClient;

    public Mono<String> sayHello() {
        return this.webClient
            .get()
            .uri("/")
            .exchange()
            .map(response -> {
                response.releaseBody();

                return response.statusCode().is2xxSuccessful()
                    ? "UP"
                    : "DOWN";
            });
    }
}
```

The Controller:

```java
@RestController
@RequiredArgsConstructor
public class HelloController {

    private final HelloService helloService;

    @GetMapping("/hello")
    public Mono<String> sayHello() {
        return this.helloService.sayHello();
    }
}
```

I perform 20 calls (curl http://localhost:8080/hello), then greps the total number of connections (curl http://localhost:8081/prometheus | grep "total_connections). The output above are the grep results.

## Possible Solution
No idea where it comes from but investigating a bit further, it seems the Spring Boot 2.2.3.RELEASE was already broken. So the issue may be a bit older.

## Your Environment
Reactor Netty versions: 0.9.2.RELEASE (OK) to 0.9.5.RELEASE (KO)
JDK: 1.8+ (1.8.0.242 and 11.05)
OS = Linux pop-os 5.3.0-7642-generic #34~1584408018~19.10~21df4b1-Ubuntu SMP Tue Mar 17 13:38:51 UTC  x86_64 x86_64 x86_64 GNU/Linux

Declared dependencies in pom (I used Spring starter generator with web flux and actuator, only 2 dependencies were added, prometheus and lombok):

```xml
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
        </dependency>
    </dependencies>
```

### PR DESCRIPTION
**Pull request by violetagg**
Fixes #1041

### CODE REVIEW

File: src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java [hunk 1]
```diff
@@ -60,7 +60,7 @@
 	final ConcurrentMap<MeterKey, Timer> addressResolverTimeCache = PlatformDependent.newConcurrentHashMap();
 
 
-	public MicrometerChannelMetricsRecorder(String name, String protocol) {
+	protected MicrometerChannelMetricsRecorder(String name, String protocol) {
```
Comment (simonbasle) [inline src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java]: this is an API breaking change, since the class itself is public. but we already made a similar breaking change in 0.9.3 (the reverse actually, removing a `protected` 3 args constructor to add the current `public` constructor)...

Comment (violetagg) [reply src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java]: ok I'll revert it to `public`
