### PR TITLE
Remove WeakHashMap cache

### LINKED ISSUE #1790: WeakHashMap access in PooledConnectionProvider.acquire should be synchronized
## Expected Behavior

Normal cpu usage

## Actual Behavior

High cpu usage. Especially in threads named parallel-xx. A thread dump shows something like:

```
"parallel-7" #79 daemon prio=5 os_prio=0 cpu=2574808.75ms elapsed=8739.80s tid=0x00007efcc804e000 nid=0x7a waiting for monitor entry  [0x00007efcc19f2000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@11.0.12/Unknown Source)
        - waiting to lock <0x00000000a579e610> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:116)
        at reactor.netty.resources.PooledConnectionProvider$$Lambda$1306/0x0000000840b0ec40.accept(Unknown Source)
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
...
"parallel-8" #80 daemon prio=5 os_prio=0 cpu=1131411.46ms elapsed=8739.80s tid=0x00007efcc804f800 nid=0x7b runnable  [0x00007efcc18f0000]
   java.lang.Thread.State: RUNNABLE
        at java.util.WeakHashMap.put(java.base@11.0.12/Unknown Source)
        at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$0(PooledConnectionProvider.java:130)
        at reactor.netty.resources.PooledConnectionProvider$$Lambda$1307/0x0000000840b0e040.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@11.0.12/Unknown Source)
        - locked <0x00000000a57af6b8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:116)
        at reactor.netty.resources.PooledConnectionProvider$$Lambda$1306/0x0000000840b0ec40.accept(Unknown Source)
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)

```

Looks like thread parallel-7 is blocked on the ConcurrentHashMap in PooledConnectionProvider, because the lambda in acquire uses a WeakHashMap which is notorious for endless loops as far as a google search shows.

## Steps to Reproduce

Our application connects to multiple servers to pull some xml data continuously i.e. retries lost connections, data errors etc.. This happens after it works for some time and while probably retrying some connections concurrently.

## Possible Solution

Wrap in a synchronized block or use a concurrent implementation as suggested in WeakHashMap javadoc

> A synchronized WeakHashMap may be constructed using the Collections.synchronizedMap method.

## Your Environment

* Reactor version(s) used: reactor-core 3.4.6 reactor-netty 1.0.7
* Other relevant libraries versions (eg. `netty`, ...): all in spring boot 4.5.1
* JVM version (`java -version`): openjdk version "11.0.11" 2021-04-20
* OS and version (eg. `uname -a`): Ubuntu 18.04 4.15.0-74-generic

### PR DESCRIPTION
**Pull request by violetagg**
The pool and the metrics are one and the same object.
The implementation already keeps all pools in a ConcurrentMap.
Add test to keep track that the pool and the metrics are the same object.

Fixes #1790

### CODE REVIEW

File: reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java [hunk 1]
```diff
@@ -465,6 +465,64 @@ void testDisposeInactivePoolsInBackground() throws Exception {
...
+					         .port(disposableServer.port())
+					         .wiretap(true)
+					         .connectNow();
+
+			assertThat(provider.channelPools).hasSize(1);
+
+			@SuppressWarnings({"unchecked", "rawtypes"})
+			InstrumentedPool<DefaultPooledConnectionProvider.PooledConnection> channelPool =
+					provider.channelPools.values().toArray(new InstrumentedPool[0])[0];
+			assertThat(channelPool.metrics()).isSameAs(channelPool);
```
Comment (simonbasle) [inline reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java:514]: there is a lot of ceremony in this test. I would consider adding a comment, or better: changing the assertion's description or error message so that if it ever fails, it becomes clear this was asserting an assumption about reactor-pool's implementation (that the pool and the `metrics()` are one and the same)

**Review by OlegDokuka — APPROVED** [review]
LGTM

File: reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java (hunk 1 above)
Comment (simonbasle) [reply reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java:514]:
```suggestion
			assertThat(channelPool.metrics())
				.withFailMessage("Reactor-netty relies on Reactor-pool instrumented pool.metrics() to be the pool instance itself, got <%s> and <%s>", 
				channelPool.metrics(), channelPool)
				.isSameAs(channelPool);
```

**Review by simonbasle — CHANGES_REQUESTED** [review]

**Review by simonbasle — APPROVED** [review]

**Comment by violetagg** [comment]
@OlegDokuka @simonbasle thanks for the review!
