### PR TITLE
fix #1152 Ensure newSocketStream() is not invoked when obtaining information for the channel class

### LINKED ISSUE #1152: Apparent file descriptor leak after upgrading from 0.9.7.RELEASE to 0.9.8.RELEASE
Yesterday I upgraded one of our services from reactor-netty 0.9.7.RELEASE to 0.9.8.RELEASE as well as Project Reactor from Dysprosium-SR7 to Dysprosium-SR8.

The service is deployed in multiple roles, the one affected by the regression is doing HTTP scraping and upload using WebClient (the ones just exposing REST services via WebFlux seem unaffected).

This morning the instance crashed (killed by Linux kernel OOM killer). Looking at the Micrometer Grafana dashboard shows that the instance accumulated nearly 180.000 file descriptors before crashing. I have since reverted reactor-netty to 0.9.7.RELEASE (but left Project Reactor at Dysprosium-SR8). This eliminates the issues, which hints at some kind of regression in reactor-netty 0.9.8.RELEASE.

The following dashboard panel nicely shows the behavior of the different versions:

image

Phase 1 (until about 19:00): reactor-netty 0.9.7 and Dysprosium-SR7 (no handles leaking)
Phase 2 (from 19:00 till 10:30): reactor-netty 0.9.8 and Dysprosium-SR8 (handles leaking)
Crash and Restart @ 10:30
Phase 3 (from 10:30 till 11:00): reactor-netty 0.9.8 and Dysprosium-SR8 (handles leaking)
Phase 4 (since 11:00): reactor-netty 0.9.7 and Dysprosium-SR8 (no handles leaking)

At the moment, that's all evidence I currently have. :-/

## Your Environment

* Reactor version(s) used: Dysprosium-SR8
* Other relevant libraries versions (eg. `netty`, ...): netty 4.1.50.Final, Spring Boot 2.3.1.RELEASE
* JVM version (`javar -version`): OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
* OS and version (eg `uname -a`): Linux hydra 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by violetagg**
This can happen when EpollSocketChannel etc. is constructed.
Fixes #1152

### CODE REVIEW

File: src/main/java/reactor/netty/resources/LoopResources.java [hunk 1]
```diff
@@ -187,6 +187,23 @@ static LoopResources create(String prefix) {
 		return channelFactory.getChannel(channelType);
 	}
 
+	/**
+	 * Callback for a {@link Channel} selection.
```
Comment (simonbasle) [inline src/main/java/reactor/netty/resources/LoopResources.java:191]: this javadoc must be updated

Comment (violetagg) [reply src/main/java/reactor/netty/resources/LoopResources.java]: fixed
