### PR TITLE
Ensure the correct Context is provided to ContextAwareHttpServerMetricsRecorder

### LINKED ISSUE #1854: ContextView in default implementations before ContextAwareHttpServerMetricsRecorder
I am attempting to make use of the new APIs `ContextAwareHttpServerMetricsRecorder` to capture and record HTTP server metrics.  I am finding that the `ContextView` being passed to any of the methods is always empty.  This seems to be the result of the default implementation of `ConnectionObserver#currentContext` returning `Context.empty()` and some of the delegating implementations aren't implementing that method.  For example, `ServerTransport.ChildObserver` never delegates the method to `this.childObs.currentContext()` for the configured child observer.

## Expected Behavior
The `ContextView` should contain some context entries, at least those configured on the child ConnectionObservers.

## Actual Behavior
The `ContextView` is always empty.

## Steps to Reproduce
[Gist](https://gist.github.com/HaloFour/a08c5db29af2df18a27b849430d2eed9)

## Possible Solution
Work through the implementations of `ConnectionObserver` to find those that should delegate to a child instance of the interface.

## Your Environment

* Reactor version(s) used: `io.projectreactor.netty:reactor-netty-http:1.0.11`
* JVM version (`java -version`): 17

### PR DESCRIPTION
**Pull request by violetagg**
Fixes #1854

### CODE REVIEW

**Review by pderop — APPROVED** [review]
LGTM

File: reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java [hunk 1]
```diff
@@ -955,7 +956,9 @@ public void onStateChange(Connection connection, State newState) {
 						log.debug(format(connection.channel(), "Handler is being applied: {}"), handler);
 					}
 					HttpServerOperations ops = (HttpServerOperations) connection;
-					Mono<Void> mono = Mono.fromDirect(handler.apply(ops, ops));
+					Mono<Void> mono = Mono.deferContextual(Mono::just)
+					                      .doOnNext(ctx -> ops.currentContext = Context.of(ctx))
+					                      .then(Mono.fromDirect(handler.apply(ops, ops)));
```
Comment (simonbasle) [inline reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java:961]: I would avoid extra couple operators (doOnNext, then) by setting the `ops.currentContext` and returning the `fromDirect` inside the `deferContextual` lambda.

**Review by simonbasle — CHANGES_REQUESTED** [review]

File: reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java (hunk 1 above)
Comment (simonbasle) [reply reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java:961]: as discussed, this suggestion doesn't really work because the `catch` clause below depends on `handler#apply` throwing at assembly time. applying the function outside of `deferContextual` should work though.

Comment (violetagg) [reply reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java]: fixed

**Comment by violetagg** [comment]
@simonbasle @pderop Thanks for the review!
