### PR TITLE
fix #995 Add API for disabling retry support for HTTP client

### LINKED ISSUE #995: opt-out of connection retry
As a part of http tracing interop, I noticed reactor-netty's HttpClient uniquely has a retry-once on connection-reset behavior, which is not possible to disable. I'd like to be able to disable this.

## Motivation
I'd like to improve the quality of trace instrumentation without disabling or special-casing the part that tests traces produced in connection error https://github.com/spring-cloud/spring-cloud-sleuth/pull/1554

## Desired solution
I'd like a way to disable the retry on connection fail.

## Considered alternatives
We could rewrite the behavior of Brave's test framework to work around this, but it seems odd especially as several new and old clients are able to control retry behavior.

## Additional context
According to @violetagg, HttpClient will retry once ONLY in cases of Connection reset by peer

https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L666

### PR DESCRIPTION
**Pull request by violetagg**
Fixes #995

### CODE REVIEW

**Comment by violetagg** [comment]
the failing test is not related

File: src/main/java/reactor/netty/http/client/HttpClient.java [hunk 1]
```diff
@@ -716,6 +716,24 @@ public final HttpClient keepAlive(boolean keepAlive) {
...
+	/**
+	 * Enable or disable {@code retry once} support for the outgoing request when
+	 * {@link reactor.netty.channel.AbortedException#isConnectionReset(Throwable)}.
+	 * By default {@code retry once} is enabled.
+	 *
+	 * @param retryEnabled true if retry should be enabled, false otherwise
+	 *
+	 * @return a new {@link HttpClient}
+	 */
+	public final HttpClient retry(boolean retryEnabled) {
```
[the remark this answers is not in the document]
Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: changed the method name to `retryEnabled`

**Comment by violetagg** [comment]
Added new callback `doOnRetryEnabled`

File: src/main/java/reactor/netty/http/client/HttpClient.java [hunk 2]
```diff
@@ -657,7 +657,22 @@ public final HttpClient doAfterResponse(BiConsumer<? super HttpClientResponse, ?
...
+	 * Setup a callback called when {@link HttpClientResponse} failed with
+	 * {@link reactor.netty.channel.AbortedException#isConnectionReset(Throwable)}
+	 * and {@link HttpClientState#RETRY_ENABLED} has been emitted.
+	 *
+	 * @param doOnRetryEnabled a callback called when {@link HttpClientResponse} failed with
+	 * {@link reactor.netty.channel.AbortedException#isConnectionReset(Throwable)}
+	 *
+	 * @return a new {@link HttpClient}
+	 */
+	public final HttpClient doOnRetryEnabled(BiConsumer<? super HttpClientResponse, ? super Connection> doOnRetryEnabled) {
```
Comment (adriancole) [inline src/main/java/reactor/netty/http/client/HttpClient.java]: I suppose this is intended to allow tagging of the error that resulted in repeating the other events again? Or when this is called, it is not going to call something else maybe you can look at this state diagram and comment expectations here https://github.com/square/okhttp/blob/master/docs/events.md#events-with-retries-and-follow-ups

File: src/main/java/reactor/netty/http/client/HttpClient.java [hunk 3]
```diff
@@ -657,7 +657,22 @@ public final HttpClient doAfterResponse(BiConsumer<? super HttpClientResponse, ?
...
 	public final HttpClient doAfterResponseSuccess(BiConsumer<? super HttpClientResponse, ? super Connection> doAfterResponseSuccess) {
 		Objects.requireNonNull(doAfterResponseSuccess, "doAfterResponseSuccess");
-		return new HttpClientDoOn(this, null, null, null, null, doAfterResponseSuccess);
+		return new HttpClientDoOn(this, null, null, null, null, doAfterResponseSuccess, null);
+	}
+
+	/**
+	 * Setup a callback called when {@link HttpClientResponse} failed with
+	 * {@link reactor.netty.channel.AbortedException#isConnectionReset(Throwable)}
+	 * and {@link HttpClientState#RETRY_ENABLED} has been emitted.
```
Comment (rstoyanchev) [inline src/main/java/reactor/netty/http/client/HttpClient.java]:
```suggestion
	 * Setup a callback called when {@link HttpClientResponse} failed with
	 * {@link reactor.netty.channel.AbortedException#isConnectionReset(Throwable)}
	 * and a retry to connect is about to be performed.
```

File: src/main/java/reactor/netty/http/client/HttpClientState.java [hunk 4]
```diff
@@ -42,6 +42,15 @@ public String toString() {
...
 	},
+	/**
+	 * The request is about to be retried
+	 */
+	RETRY_ENABLED() {
+		@Override
+		public String toString() {
+			return "[retry_enabled]";
+		}
+	},
```
Comment (rstoyanchev) [inline src/main/java/reactor/netty/http/client/HttpClientState.java]: Could this be called `RETRYING` perhaps? Again `RETRY_ENABLED` sounds like a config time callback.

For source code ordering, it's a bit strange to see this state in the middle of the request related ones. Perhaps it can be ordered at the top of this class since it belongs more with the base class (connection related).

File: src/main/java/reactor/netty/http/client/HttpClient.java (hunk 2 above)
Comment (adriancole) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: hard to elaborate my question without a test.

I suppose I mean.. should we expect in retry this?

doOnRequest
doOnResponseError
doOnRetry
doOnRequest
doOnResponse

or

doOnRequest
doOnRetry
doOnRequest
doOnResponse

or something else... if the former I agree we can kill the doOnRetry as long as we can see the doOnResponseError

Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: My idea is to have this flow

```
doOnRequest
doOnRetry
doOnRequest
doOnResponse
```

**Comment by violetagg** [comment]
> This description for #995 only asks for a way to disable retry. Just double checking whether the doOnRetry callback is actually needed.

The discussion for `doOnRetry` was started here
https://github.com/reactor/reactor-netty/pull/1020#issuecomment-595633152

File: src/main/java/reactor/netty/http/client/HttpClient.java (hunk 2 above)
Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: Retry is not performed for any exception so using this callback retry can be distinguish from error

File: src/main/java/reactor/netty/http/client/HttpClient.java [hunk 5]
```diff
@@ -716,6 +731,24 @@ public final HttpClient keepAlive(boolean keepAlive) {
...
+	/**
+	 * Enable or disable {@code retry once} support for the outgoing request when
+	 * {@link reactor.netty.channel.AbortedException#isConnectionReset(Throwable)}.
+	 * By default {@code retry once} is enabled.
+	 *
+	 * @param retryEnabled true if retry should be enabled, false otherwise
+	 *
+	 * @return a new {@link HttpClient}
+	 */
+	public final HttpClient retryEnabled(boolean retryEnabled) {
```
[the remark this answers is not in the document]
Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: Changed the method name to `disableRetry`

File: src/main/java/reactor/netty/http/client/HttpClient.java (hunk 3 above)
Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: done, method name changed to `doOnRetry`

File: src/main/java/reactor/netty/http/client/HttpClientState.java (hunk 4 above)
Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClientState.java]: done, changed to `RETRYING`

File: src/main/java/reactor/netty/http/client/HttpClient.java (hunk 2 above)
Comment (adriancole) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: technically it is an exception :P just a matter if the callback sees it or not. Is the response object useful here? Would it not be better to provide the underlying throwable and/or replace with doOnError? Maybe I'm reading too much into the javadoc, but it seems like this is literally in response to a Throwable.

File: src/main/java/reactor/netty/http/client/HttpClientConnect.java [hunk 6]
```diff
@@ -683,6 +640,43 @@ public boolean test(Throwable throwable) {
...
+		}
+
+		@Override
+		public void onUncaughtException(Connection connection, Throwable error) {
+			if (error instanceof RedirectClientException) {
+				if (log.isDebugEnabled()) {
+					log.debug(format(connection.channel(), "The request will be redirected"));
+				}
+			}
+			else if (AbortedException.isConnectionReset(error) && !retried) {
```
Comment (adriancole) [inline src/main/java/reactor/netty/http/client/HttpClientConnect.java]: basically it looks like a special case of error. I might say this is like doOnError, except we know it will be retried, then pass the `error` to it.

Code-wise, brave/zipkin will do nothing different that the hook is named doOnRetry vs doOnError as the behavior for any follow-up request would be the same, regardless of if reason is retry or redirect.

**Comment by violetagg** [comment]
@adriancole @rstoyanchev PTAL
I removed `doOnRetry` there will be only `doOnError` event

File: src/main/java/reactor/netty/http/client/HttpClientConnect.java [hunk 7]
```diff
@@ -512,6 +468,7 @@ public void onStateChange(Connection connection, State newState) {
 			this.websocketProtocols = configuration.websocketSubprotocols;
 			this.maxFramePayloadLength = configuration.websocketMaxFramePayloadLength;
 			this.websocketProxyPing = configuration.websocketProxyPing;
+			this.retried = !configuration.retryEnabled;
```
Comment (rstoyanchev) [inline src/main/java/reactor/netty/http/client/HttpClientConnect.java]: I think this would be easier to read as `shouldRetry`.

Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClientConnect.java]: done

File: src/test/java/reactor/netty/http/client/HttpClientTest.java [hunk 8]
```diff
@@ -1329,18 +1338,43 @@ public void testRetryNotEndlessIssue587() throws Exception {
...
+				HttpClient.create()
+				          .port(serverPort)
+				          .wiretap(true)
+				          .doOnRequest((req, conn) -> doOnRequest.getAndIncrement())
+				          .doOnError((req, t) -> doOnRequestError.getAndIncrement(),
+				                     (res, t) -> doOnResponseError.getAndIncrement());
+
+		if (retryDisabled) {
+			client = client.disableRetry(true);
+		}
```
[the remark this answers is not in the document]
Comment (violetagg) [reply src/test/java/reactor/netty/http/client/HttpClientTest.java]: done

File: src/main/java/reactor/netty/http/client/HttpClientConfiguration.java [hunk 9]
```diff
@@ -55,6 +55,7 @@
 	String                        websocketSubprotocols          = null;
 	int                           websocketMaxFramePayloadLength = 65536;
 	boolean                       websocketProxyPing             = false;
+	boolean                       retryEnabled                   = true;
```
[the remark this answers is not in the document]
Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClientConfiguration.java]: done

File: src/main/java/reactor/netty/http/client/HttpClient.java [hunk 10]
```diff
@@ -736,6 +736,25 @@ public final HttpClient keepAlive(boolean keepAlive) {
 		}
 	}
 
+	/**
+	 * Enable or disable {@code retry once} support for the outgoing request when
+	 * {@link reactor.netty.channel.AbortedException#isConnectionReset(Throwable)}.
+	 * By default {@code retry once} is enabled.
+	 *
+	 * @param disableRetry true if {@code retry once} should be disabled, false otherwise
```
[the remark this answers is not in the document]
Comment (violetagg) [reply src/main/java/reactor/netty/http/client/HttpClient.java]: done

**Comment by violetagg** [comment]
> This looks better without the extra state.
> 
> One minor comment, `HttpObserver` in `HttpClientConnect` could have remained a separate decorator class, since it has access to `handler.retried`.

agree

**Comment by adriancole** [comment]
somehow this seems to trip up redirect.. Ex when I set disableRetry my redirect tests fail that otherwise work when followRedirect(true)

```java
				.disableRetry(true)
				.followRedirect(true)
```
