### PR TITLE
fix #289 Register pool-releasing close listener only if acquired

### LINKED ISSUE #289: Regression: rejected client connection decrement pool counter
After fix for #285, spring-messaging has observed a failing test scenario with the following stack:
```
2018-02-18 14:30:27,578 WARN [tcp-client-loop-nio-1] [io.netty.util.concurrent.DefaultPromise] - An exception was thrown by io.netty.channel.pool.FixedChannelPool$4.operationComplete()
java.lang.AssertionError: null
	at io.netty.channel.pool.FixedChannelPool.decrementAndRunTaskQueue(FixedChannelPool.java:324) ~[netty-transport-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.pool.FixedChannelPool.access$600(c.java:38) ~[netty-transport-4.1.21.Final.jar:4.1.21.Final]
	at io.netty.channel.pool.FixedChannelPool$4.operationComplete(FixedChannelPool.java:305) ~[netty-transport-4.1.21.Final.jar:4.1.21.Final]
```

The stack points to an illegal counting occurring in `FixedChannelPool`. The scenario involves an immediately rejected connection to reproduce.

### PR DESCRIPTION
**Pull request by simonbasle**
Instead of setting up the close listener in the ChannelPoolHandler
channelCreated method, set it up in the PooledClientContextHandler.

This should prevent the listener to be invoked after a FixedChannelPool
has determined the channel was not healthy and has already decremented
its internal acquire counter (which would lead to a second decrement of
said counter and an assertion error).

### CODE REVIEW

**Comment by simonbasle** [comment]
please heavily challenge the relevance of this fix. adding a little background on the issue itself.

File: src/test/java/reactor/ipc/netty/resources/DefaultPoolResourcesTest.java [hunk 1]
```diff
@@ -114,4 +126,68 @@ public void disposeOnlyOnce() {
 		assertThat(closed.get()).as("pool closed only once").isEqualTo(1);
 	}
 
+	@Test
+	public void fixedPoolTwoAcquire()
+			throws ExecutionException, InterruptedException, IOException {
+		final ScheduledExecutorService service = Executors.newScheduledThreadPool(2);
+		int echoServerPort = SocketUtils.findAvailableTcpPort();
```
Comment (garyrussell) [inline src/test/java/reactor/ipc/netty/resources/DefaultPoolResourcesTest.java]: FYI, this is not entirely reliable and can cause problems on CI servers, if some other process grabs the socket. We've seen this happen once in a while, causing bogus CI build failures. 

In my projects, where possible, we've changed tests to listen on port 0 (so the OS selects the port) and then query the test server for which port was actually selected.

Not critical but worth consideration.

Comment (simonbasle) [reply src/test/java/reactor/ipc/netty/resources/DefaultPoolResourcesTest.java]: hard to do as the first part of the test checks what happens when the host is initially unreachable. crossing fingers for CI :(
