### PR TITLE
fix #1418 let configure WebSocket version of the client

### LINKED ISSUE #1418: How to switch WebSocketClientHandshaker version
I now use spring-boot-starter-webflux:2.4.0->reactor-netty:1.0.1, the WebSocketClient handshake fails, and the reactor-netty uses WebSocketVersion.V13, can this be dynamic?

### PR DESCRIPTION
**Pull request by aneveu**
@violetagg could you please tell me if the way to manage `null` and `UNKNOWN` version is fine for you?

### CODE REVIEW

**Comment by violetagg** [comment]
@aneveu As discussed let's fail when `NULL` and `UNKNOWN` as we expect that when a user wants to provide a version he/she will provide a concrete version different than the default one.

**Review by violetagg — CHANGES_REQUESTED** [review]

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java [hunk 1]
```diff
@@ -67,7 +68,7 @@ private void failOnClientServerError(
 				          .port(httpServer.port())
 				          .wiretap(true)
 				          .headersWhen(h -> login(httpServer.port()).map(token -> h.set("Authorization", token)))
-				          .websocket(WebsocketClientSpec.builder().protocols(clientSubprotocol).build())
+				          .websocket(WebsocketClientSpec.builder().version(WebSocketVersion.V08).protocols(clientSubprotocol).build())
```
Comment (violetagg) [inline reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:71]: Instead of adding here a configuration for the version, I suggest to have a dedicated test for this feature.
Wdyt?

Comment (aneveu) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:71]: Better idea indeed, I'll be able to test failing cases this way

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java [hunk 2]
```diff
@@ -88,4 +94,34 @@ private void failOnClientServerError(
 		                 .uri("/login")
 		                 .responseSingle((res, buf) -> Mono.just(res.status().code() + ""));
 	}
+
+	@Test
+	public void testConfigureWebSocketVersion(){
+		DisposableServer httpServer = HttpServer.create()
+				.port(0)
+				.handle((in, out) -> out.sendWebsocket((i, o) -> o.sendString(Mono.just("test"))))
+				.bindNow();
```
Comment (violetagg) [inline reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:103]: I propose to check on the server that the version that was sent by the client is really `8`.
You can do that with checking this header `sec-websocket-version: 8`

**Comment by violetagg** [comment]
@simonbasle PTAL

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java (hunk 2 above)
Comment (aneveu) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:103]: great, thanks for the tip!

File: reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientSpecImpl.java [hunk 3]
```diff
@@ -15,15 +15,23 @@
...
 
+import io.netty.handler.codec.http.websocketx.WebSocketVersion;
 import reactor.netty.http.websocket.WebsocketSpecImpl;
 
 /**
  * @author Violeta Georgieva
  * @since 0.9.7
  */
 final class WebsocketClientSpecImpl extends WebsocketSpecImpl implements WebsocketClientSpec {
+	private final WebSocketVersion version;
```
Comment (simonbasle) [inline reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientSpecImpl.java:26]: nitpick: add a blank line here

File: reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientSpec.java [hunk 4]
```diff
@@ -42,10 +55,30 @@ static Builder builder() {
 	}
 
 	final class Builder extends WebsocketSpec.Builder<Builder> {
+		WebSocketVersion version = WebSocketVersion.V13;
```
Comment (simonbasle) [inline reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientSpec.java:58]: nitpick: blank line before

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java (hunk 2 above)
Comment (simonbasle) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:103]: good idea! please do capture the header in `handle` above in order to verify it

**Review by simonbasle — CHANGES_REQUESTED** [review]

**Review by violetagg — APPROVED** [review]

**Comment by violetagg** [comment]
@aneveu You somehow reverted the test for the header?

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java [hunk 5]
```diff
@@ -15,9 +15,13 @@
  */
 package reactor.netty.http.client;
 
+import com.sun.org.apache.xpath.internal.Arg;
```
Comment (simonbasle) [inline reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:18]: bad import I think

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java [hunk 6]
```diff
@@ -54,73 +58,77 @@ private void failOnClientServerError(
...
-				                        int token = Integer.parseInt(req.requestHeaders().get("Authorization"));
-				                        if (token >= 400) {
-				                            return res.status(token).send();
-				                        }
-				                        return res.sendWebsocket((i, o) -> o.sendString(Mono.just("test")),
-				                                WebsocketServerSpec.builder().protocols(serverSubprotocol).build());
-				                    }))
-				          .wiretap(true)
-				          .bindNow();
+						.port(0)
```
Comment (simonbasle) [inline reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:61]: please configure your IDE to not run formatting on the whole file (only changed line, ideally)

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java [hunk 7]
```diff
@@ -54,73 +58,77 @@ private void failOnClientServerError(
...
 	@Test
-	public void testConfigureWebSocketVersion(){
+	public void testConfigureWebSocketVersion() {
+		ArgumentCaptor<HttpHeaders> argumentCaptor = ArgumentCaptor.forClass(HttpHeaders.class);
+
 		DisposableServer httpServer = HttpServer.create()
 				.port(0)
-				.handle((in, out) -> out.sendWebsocket((i, o) -> o.sendString(Mono.just("test"))))
+				.handle((in, out) -> {
+					assertThat(in.requestHeaders().get("sec-websocket-version")).isEqualTo("8");
```
Comment (simonbasle) [inline reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:109]: does the `AssertionError` escape the `handle` and actually fails the test?
I had a doubt and verified locally, it seems to log the assertion error but then hangs...

another way would be for the `sendString` below to return the content of the header, and then we can assert it in the `HttpClient...block()` call, as the body of the response.

**Review by simonbasle — CHANGES_REQUESTED** [review]

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java (hunk 7 above)
Comment (simonbasle) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:109]: just to be clear: the test passes in its current form _because the assertion succeeds_. If you change it to `isEqualTo("foo")` an `AssertionError` is logged but the test then hangs.

Comment (simonbasle) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:109]: also, it seems you don't need Mockito at all anymore

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java [hunk 8]
```diff
@@ -48,44 +58,78 @@ private void failOnClientServerError(
...
+				.bindNow();
+
+		 HttpClient.create()
+				.port(httpServer.port())
+				.wiretap(true)
+				.websocket(WebsocketClientSpec.builder().version(WebSocketVersion.V08).build())
+				.uri("/test")
+				.handle((in, out) -> in.receive().aggregate().asString())
+				.collectList()
+				.block();
```
Comment (violetagg) [inline reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:122]: I suggest to specify timeout for the `block` invocation

**Review by violetagg — CHANGES_REQUESTED** [review]

File: reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java (hunk 8 above)
Comment (simonbasle) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:122]: but then if the test fails the error message would be one of timeout... unless you're suggesting to do that in addition to extracting the assertion to perform it on the result of the block?

Comment (violetagg) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java:122]: in addition to what you suggested
We always use timeout for `block`, `verify` etc in order to prevent tests hang forever in something happens

**Review by simonbasle — APPROVED** [review]

**Review by violetagg — APPROVED** [review]
