### PR TITLE
fix #1257 Target host should not be resolved when proxy is configured (1.0.0)

### LINKED ISSUE #1257: Target host should not be resolved when proxy is configured
When HTTP client is configured with proxy, it should not try to resolve the target host.  Resolving the target address should be proxy's responsibility:

```java
HttpClient.create()
    .baseUrl(""http://some-random-locally-not-resolvable-address-12345.com"")
    .metrics(metricsEnabled, () -> MicrometerHttpClientMetricsRecorder.INSTANCE)
    .proxy(proxyOptions);
```

## Expected Behavior

Target host should not be attempted to be resolved.

## Actual Behavior

- 0.9.x:
  - Metrics disabled: Works as expected and does not attempt to resolve the target host.
  - Metrics enabled: throws `UnknownHostException`.

- 1.0.0-M1: thrown `UnknownHostException`.

## Steps to Reproduce

I will be sharing a PR shortly.

### PR DESCRIPTION
**Pull request by violetagg**
A forward merge of the fix for #1257 (0.9.x) cannot be achieved because of
the changes in the implementation, so the fix for 1.0.0 is done separately.

### CODE REVIEW

File: reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java [hunk 1]
```diff
@@ -203,6 +204,39 @@ public void shouldNotResolveTargetHostnameWhenMetricsDisabled() {
...
+		client.proxy(ops -> ops.type(ProxyProvider.Proxy.HTTP)
+		                       .host("localhost")
+		                       .port(hoverflyRule.getProxyPort()))
+		      .doOnConnect(config -> resolver2.set(config.resolver()))
+		      .get()
+		      .uri(LOCALLY_NOT_RESOLVABLE_ADDRESS)
+		      .responseSingle((response, body) -> Mono.zip(body.asString(),
+		                                                   Mono.just(response.responseHeaders())))
+		      .block(Duration.ofSeconds(30));
+
```
Comment (anilgursel) [inline reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java:233]: Should we add another http call here after the proxy just to verify that we are still able to make the calls without proxy and proxy configuration actually modified a copy?

```java
client.doOnConnect(config -> resolver1.set(config.resolver()))
		      .get()
		      .uri("http://example.com")
		      .responseSingle((response, body) -> Mono.zip(body.asString(),
		                                                   Mono.just(response.responseHeaders())))
		      .block(Duration.ofSeconds(30));
```

Comment (violetagg) [reply reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java:233]: yep let's extend the test
