### PR TITLE
Ensure the buffer is not released twice

### LINKED ISSUE #3406: Repeatedly releasing buf ,IllegalReferenceCountException: refCnt: 0, decrement: 1
## Expected Behavior

no exception, bytebuf release once.

## Actual Behavior

2024-08-23 13:47:13.682 ERROR [     demo-nio-1] [324] reactor.core.publisher.Operators Operator called default onErrorDropped
 io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:298)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:403)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:425)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

## Steps to Reproduce

Run the following code, and exec `telnet 127.0.0.1 1024` ,  enter 1, 2, 3, 4 in sequence。  
 "bing.com"  will close my client connection. this bug can recurrent. 

```java

package com;

import com.start.Environment;
import io.netty.channel.ChannelOption;
import io.netty.handler.logging.LogLevel;
import io.netty.util.ReferenceCountUtil;
import reactor.core.publisher.Mono;
import reactor.netty.Connection;
import reactor.netty.resources.LoopResources;
import reactor.netty.tcp.TcpClient;
import reactor.netty.tcp.TcpServer;
import reactor.netty.transport.logging.AdvancedByteBufFormat;

public class Test {

    public static void main(String[] args) {
        LoopResources loopResources = LoopResources.create("demo", 1, 1, true);

        // client
        Mono<? extends Connection> connect = TcpClient.newConnection()
                .wiretap("demo", LogLevel.INFO, AdvancedByteBufFormat.HEX_DUMP)
                .runOn(loopResources)
                .option(ChannelOption.TCP_NODELAY, true)
                .host("bing.com")
                .port(443)
                .connect();
        Connection client = connect.block();

        //service
        TcpServer service = TcpServer.create()
                .runOn(loopResources)
                .option(ChannelOption.AUTO_READ, false)
                .childOption(ChannelOption.TCP_NODELAY, true)
                .doOnConnection(subConn -> {
                    subConn.inbound().receiveObject().concatMap(data -> {

                                //send data from service to client
                                ReferenceCountUtil.retain(data);
                                return client.outbound().sendObject(data);
                            }, 0)
                            .checkpoint()
                            .subscribe(null, e -> {
                                e.printStackTrace();
                            });

                })
                .wiretap("SERVER", Environment.LEVEL, Environment.FORMAT)
                .host("0.0.0.0")
                .port(1024);

        //block
        service.bindNow().onDispose().block();
    }
}

```

## Possible Solution

image

As shown in the above figure, onCleanup function will use `safeRelease` to release message，but I retain it at my code  

image

1. on message read in netty , refCnt = 1
2. reactor dispatch message to my code , I retain it, refCnt = 2
3. I write message to outbound , refCnt = 1 (even if it fails, netty will release it)
4. reactor onCleanup will release it once, refCnt = 0
5. reactor finally code after `onNext` release it . throw exception.

## Your Environment

* Reactor version(s) used:  
  - reactor-netty-core 3.6.9
  - reactor-netty-core 1.1.22
* Other relevant libraries versions (eg. `netty`, ...):
  - netty 4.1.112.Final
* JVM version (`java -version`):
  - OpenJDK 64-Bit Server VM Zulu11.68+17-CA (build 11.0.21+9-LTS, mixed mode) 
* OS and version (eg. `uname -a`):
  - MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### PR DESCRIPTION
**Pull request by violetagg**
When `NettyOutbound#sendObject(java.lang.Object)` is used, it is Netty's responsibility to release the buffer on success/error

Fixes #3406

### CODE REVIEW

File: reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java [hunk 1]
```diff
@@ -721,42 +722,41 @@ public void onStateChange(Connection connection, State newState) {
...
 
 		static final Runnable EMPTY_CLEANUP = () -> {};
 
-
 		OutboundThen(NettyOutbound source, Publisher<Void> thenPublisher) {
 			this(source, thenPublisher, EMPTY_CLEANUP);
 		}
 
+		// This construction is used only with ChannelOperations#sendObject
+		// The implementation relies on Netty's promise that Channel#writeAndFlush will release the buffer on success/error
```
Comment (chemicL) [inline reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java:737]: It would be worth to add another line comment that the release hear happens only in case when we are sure that the processing doesn't delegate to Netty because of some failure before the exchange can be continued in the `thenPublisher` - which in a regular case takes ownership of the buffer.

**Review by chemicL — APPROVED** [review]
I left just a small commenting request but otherwise it looks that this addresses the issue.

**Comment by violetagg** [comment]
@chemicL Thanks for the review!
