### PR TITLE
Expose an API for obtaining all cookies with one and the same name

### LINKED ISSUE #1641: Cookie decoding for multiple cookies with same name has issues
## Expected Behavior

`Cookies.getCachedCookies()` should return multiple cookies with same name if present in header

## Actual Behavior

`Cookies.getCachedCookies()` returns only the first parsed cookie with a particular name

## Steps to Reproduce

Send a request parsed by rector-netty with a cookie header like
`test-cookie=ABC;test-cookie=DEF`

the getCookies() returns only the first cookie, the second is ignored

## Possible Solution

The bug is in line: https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java#L117

this should be replaced with call to: 
`decode = ((ServerCookieDecoder) decoder).decodeAll(aCookieHeader);`

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...): 0.9.3 but the bug is present even in 1.0.7
* JVM version (`java -version`): 11
* OS and version (eg. `uname -a`): Linux

### PR DESCRIPTION
**Pull request by violetagg**
https://datatracker.ietf.org/doc/html/rfc6265#section-4.2.2

Although cookies are serialized linearly in the `Cookie` header,
servers SHOULD NOT rely upon the serialization order.  In particular,
if the `Cookie` header contains two cookies with the same name (e.g.,
that were set with different `Path` or `Domain` attributes), servers
SHOULD NOT rely upon the order in which these cookies appear in the
header.

Fixes #1641

### CODE REVIEW

File: reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java [hunk 1]
```diff
@@ -104,27 +111,35 @@ private Cookies(HttpHeaders nettyHeaders, CharSequence cookiesHeaderName, boolea
...
+		markReadCookies();
 		return cachedCookies;
 	}
+
+	protected List<String> allCookieHeaders() {
+		return nettyHeaders.getAll(cookiesHeaderName);
+	}
+
+	protected final boolean hasReadCookies() {
+		return state == READ;
```
Comment (simonbasle) [inline reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java:135]: the atomic field updater can only guarantee atomicity and memory-ordering of the write operations if all write operations are performed through it rather than the volatile variable.

for that reason, this should be `STATE.set(this, READ)`.

(reading from the volatile is always ok)

**Review by simonbasle — CHANGES_REQUESTED** [review]
small improvement to existing code requested (see comment, sorry I posted it outside the review)

File: reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java (hunk 1 above)
Comment (violetagg) [reply reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java:135]: but here `hasReadCookies` we want just to check the state we do not want to set it or I miss something?

Comment (simonbasle) [reply reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java:135]: oh gods, that's right 🤦 I was looking on the left hand side seeing `state = READ` and here `state == READ` and my brain jumped to conclusions 😆

all good, nothing to see here, move along

**Review by simonbasle — APPROVED** [review]

File: reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java (hunk 1 above)
Comment (violetagg) [reply reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java:135]: thanks a lot
